# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pocsuite.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pocsuite.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=b'Z\004grpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0epocsuite.proto\x12\x04grpc\"(\n\nPocRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1d\n\x0bPocResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32p\n\x07PocScan\x12\x31\n\x08XiangJia\x12\x10.grpc.PocRequest\x1a\x11.grpc.PocResponse\"\x00\x12\x32\n\tXiangJian\x12\x10.grpc.PocRequest\x1a\x11.grpc.PocResponse\"\x00\x42\x06Z\x04grpcb\x06proto3'
)




_POCREQUEST = _descriptor.Descriptor(
  name='PocRequest',
  full_name='grpc.PocRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num1', full_name='grpc.PocRequest.num1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num2', full_name='grpc.PocRequest.num2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=64,
)


_POCRESPONSE = _descriptor.Descriptor(
  name='PocResponse',
  full_name='grpc.PocResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='grpc.PocResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['PocRequest'] = _POCREQUEST
DESCRIPTOR.message_types_by_name['PocResponse'] = _POCRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PocRequest = _reflection.GeneratedProtocolMessageType('PocRequest', (_message.Message,), {
  'DESCRIPTOR' : _POCREQUEST,
  '__module__' : 'pocsuite_pb2'
  # @@protoc_insertion_point(class_scope:grpc.PocRequest)
  })
_sym_db.RegisterMessage(PocRequest)

PocResponse = _reflection.GeneratedProtocolMessageType('PocResponse', (_message.Message,), {
  'DESCRIPTOR' : _POCRESPONSE,
  '__module__' : 'pocsuite_pb2'
  # @@protoc_insertion_point(class_scope:grpc.PocResponse)
  })
_sym_db.RegisterMessage(PocResponse)


DESCRIPTOR._options = None

_POCSCAN = _descriptor.ServiceDescriptor(
  name='PocScan',
  full_name='grpc.PocScan',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=97,
  serialized_end=209,
  methods=[
  _descriptor.MethodDescriptor(
    name='XiangJia',
    full_name='grpc.PocScan.XiangJia',
    index=0,
    containing_service=None,
    input_type=_POCREQUEST,
    output_type=_POCRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='XiangJian',
    full_name='grpc.PocScan.XiangJian',
    index=1,
    containing_service=None,
    input_type=_POCREQUEST,
    output_type=_POCRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POCSCAN)

DESCRIPTOR.services_by_name['PocScan'] = _POCSCAN

# @@protoc_insertion_point(module_scope)
