# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pocsuite.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pocsuite.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=b'Z\004grpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0epocsuite.proto\x12\x04grpc\"e\n\nPocRequest\x12\x0f\n\x07\x65xploit\x18\x01 \x01(\x08\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\x12\x10\n\x08\x61sset_id\x18\x04 \x01(\t\x12\x13\n\x0bpoc_plugins\x18\x05 \x03(\t\"\xbe\x03\n\x0bPocResponse\x12\x35\n\nVerifyInfo\x18\x01 \x03(\x0b\x32!.grpc.PocResponse.VerifyInfoEntry\x12\x37\n\x0b\x45xploitInfo\x18\x02 \x03(\x0b\x32\".grpc.PocResponse.ExploitInfoEntry\x12\x39\n\x0cWebshellInfo\x18\x03 \x03(\x0b\x32#.grpc.PocResponse.WebshellInfoEntry\x12\x35\n\nTrojanInfo\x18\x04 \x03(\x0b\x32!.grpc.PocResponse.TrojanInfoEntry\x1a\x31\n\x0fVerifyInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x32\n\x10\x45xploitInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x33\n\x11WebshellInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x31\n\x0fTrojanInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32:\n\x07PocScan\x12/\n\x06Verify\x12\x10.grpc.PocRequest\x1a\x11.grpc.PocResponse\"\x00\x42\x06Z\x04grpcb\x06proto3'
)




_POCREQUEST = _descriptor.Descriptor(
  name='PocRequest',
  full_name='grpc.PocRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exploit', full_name='grpc.PocRequest.exploit', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target', full_name='grpc.PocRequest.target', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='grpc.PocRequest.command', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='asset_id', full_name='grpc.PocRequest.asset_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='poc_plugins', full_name='grpc.PocRequest.poc_plugins', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=125,
)


_POCRESPONSE_VERIFYINFOENTRY = _descriptor.Descriptor(
  name='VerifyInfoEntry',
  full_name='grpc.PocResponse.VerifyInfoEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='grpc.PocResponse.VerifyInfoEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='grpc.PocResponse.VerifyInfoEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=418,
)

_POCRESPONSE_EXPLOITINFOENTRY = _descriptor.Descriptor(
  name='ExploitInfoEntry',
  full_name='grpc.PocResponse.ExploitInfoEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='grpc.PocResponse.ExploitInfoEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='grpc.PocResponse.ExploitInfoEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=470,
)

_POCRESPONSE_WEBSHELLINFOENTRY = _descriptor.Descriptor(
  name='WebshellInfoEntry',
  full_name='grpc.PocResponse.WebshellInfoEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='grpc.PocResponse.WebshellInfoEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='grpc.PocResponse.WebshellInfoEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=523,
)

_POCRESPONSE_TROJANINFOENTRY = _descriptor.Descriptor(
  name='TrojanInfoEntry',
  full_name='grpc.PocResponse.TrojanInfoEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='grpc.PocResponse.TrojanInfoEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='grpc.PocResponse.TrojanInfoEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=574,
)

_POCRESPONSE = _descriptor.Descriptor(
  name='PocResponse',
  full_name='grpc.PocResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='VerifyInfo', full_name='grpc.PocResponse.VerifyInfo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ExploitInfo', full_name='grpc.PocResponse.ExploitInfo', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='WebshellInfo', full_name='grpc.PocResponse.WebshellInfo', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TrojanInfo', full_name='grpc.PocResponse.TrojanInfo', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_POCRESPONSE_VERIFYINFOENTRY, _POCRESPONSE_EXPLOITINFOENTRY, _POCRESPONSE_WEBSHELLINFOENTRY, _POCRESPONSE_TROJANINFOENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=574,
)

_POCRESPONSE_VERIFYINFOENTRY.containing_type = _POCRESPONSE
_POCRESPONSE_EXPLOITINFOENTRY.containing_type = _POCRESPONSE
_POCRESPONSE_WEBSHELLINFOENTRY.containing_type = _POCRESPONSE
_POCRESPONSE_TROJANINFOENTRY.containing_type = _POCRESPONSE
_POCRESPONSE.fields_by_name['VerifyInfo'].message_type = _POCRESPONSE_VERIFYINFOENTRY
_POCRESPONSE.fields_by_name['ExploitInfo'].message_type = _POCRESPONSE_EXPLOITINFOENTRY
_POCRESPONSE.fields_by_name['WebshellInfo'].message_type = _POCRESPONSE_WEBSHELLINFOENTRY
_POCRESPONSE.fields_by_name['TrojanInfo'].message_type = _POCRESPONSE_TROJANINFOENTRY
DESCRIPTOR.message_types_by_name['PocRequest'] = _POCREQUEST
DESCRIPTOR.message_types_by_name['PocResponse'] = _POCRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PocRequest = _reflection.GeneratedProtocolMessageType('PocRequest', (_message.Message,), {
  'DESCRIPTOR' : _POCREQUEST,
  '__module__' : 'pocsuite_pb2'
  # @@protoc_insertion_point(class_scope:grpc.PocRequest)
  })
_sym_db.RegisterMessage(PocRequest)

PocResponse = _reflection.GeneratedProtocolMessageType('PocResponse', (_message.Message,), {

  'VerifyInfoEntry' : _reflection.GeneratedProtocolMessageType('VerifyInfoEntry', (_message.Message,), {
    'DESCRIPTOR' : _POCRESPONSE_VERIFYINFOENTRY,
    '__module__' : 'pocsuite_pb2'
    # @@protoc_insertion_point(class_scope:grpc.PocResponse.VerifyInfoEntry)
    })
  ,

  'ExploitInfoEntry' : _reflection.GeneratedProtocolMessageType('ExploitInfoEntry', (_message.Message,), {
    'DESCRIPTOR' : _POCRESPONSE_EXPLOITINFOENTRY,
    '__module__' : 'pocsuite_pb2'
    # @@protoc_insertion_point(class_scope:grpc.PocResponse.ExploitInfoEntry)
    })
  ,

  'WebshellInfoEntry' : _reflection.GeneratedProtocolMessageType('WebshellInfoEntry', (_message.Message,), {
    'DESCRIPTOR' : _POCRESPONSE_WEBSHELLINFOENTRY,
    '__module__' : 'pocsuite_pb2'
    # @@protoc_insertion_point(class_scope:grpc.PocResponse.WebshellInfoEntry)
    })
  ,

  'TrojanInfoEntry' : _reflection.GeneratedProtocolMessageType('TrojanInfoEntry', (_message.Message,), {
    'DESCRIPTOR' : _POCRESPONSE_TROJANINFOENTRY,
    '__module__' : 'pocsuite_pb2'
    # @@protoc_insertion_point(class_scope:grpc.PocResponse.TrojanInfoEntry)
    })
  ,
  'DESCRIPTOR' : _POCRESPONSE,
  '__module__' : 'pocsuite_pb2'
  # @@protoc_insertion_point(class_scope:grpc.PocResponse)
  })
_sym_db.RegisterMessage(PocResponse)
_sym_db.RegisterMessage(PocResponse.VerifyInfoEntry)
_sym_db.RegisterMessage(PocResponse.ExploitInfoEntry)
_sym_db.RegisterMessage(PocResponse.WebshellInfoEntry)
_sym_db.RegisterMessage(PocResponse.TrojanInfoEntry)


DESCRIPTOR._options = None
_POCRESPONSE_VERIFYINFOENTRY._options = None
_POCRESPONSE_EXPLOITINFOENTRY._options = None
_POCRESPONSE_WEBSHELLINFOENTRY._options = None
_POCRESPONSE_TROJANINFOENTRY._options = None

_POCSCAN = _descriptor.ServiceDescriptor(
  name='PocScan',
  full_name='grpc.PocScan',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=576,
  serialized_end=634,
  methods=[
  _descriptor.MethodDescriptor(
    name='Verify',
    full_name='grpc.PocScan.Verify',
    index=0,
    containing_service=None,
    input_type=_POCREQUEST,
    output_type=_POCRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POCSCAN)

DESCRIPTOR.services_by_name['PocScan'] = _POCSCAN

# @@protoc_insertion_point(module_scope)
